apiVersion: apps/v1
kind: Deployment
metadata:
  name: appgear-m13-workspaces-vcluster-controller
  labels:
    appgear.io/module-id: M13
    appgear.io/module-name: "workspaces-vcluster"
spec:
  replicas: 1
  selector:
    matchLabels:
      appgear.io/module-id: M13
      appgear.io/module-name: "workspaces-vcluster"
      appgear.io/role: controller
  template:
    metadata:
      labels:
        appgear.io/module-id: M13
        appgear.io/module-name: "workspaces-vcluster"
        appgear.io/role: controller
    spec:
      containers:
        - name: controller
          image: alpine:3.19
          ports:
            - containerPort: 80
          env:
            - name: MODULE_ID
              value: "M13"
            - name: MODULE_NAME
              value: "workspaces-vcluster"
            - name: INTENDED_COMPONENTS
              value: "vcluster,tenants,workspaces,quotas"
