apiVersion: apps/v1
kind: Deployment
metadata:
  name: appgear-m02-borda-controller
  labels:
    appgear.io/module-id: M02
    appgear.io/module-name: "borda"
spec:
  replicas: 1
  selector:
    matchLabels:
      appgear.io/module-id: M02
      appgear.io/module-name: "borda"
      appgear.io/role: controller
  template:
    metadata:
      labels:
        appgear.io/module-id: M02
        appgear.io/module-name: "borda"
        appgear.io/role: controller
    spec:
      containers:
        - name: controller
          image: nginx:stable
          ports:
            - containerPort: 80
          env:
            - name: MODULE_ID
              value: "M02"
            - name: MODULE_NAME
              value: "borda"
            - name: INTENDED_COMPONENTS
              value: "traefik,coraza,kong,istio,tailscale"
