apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appgear-edge

resources:
  - namespace.yaml

configMapGenerator:
  - name: appgear-m02-metadata
    literals:
      - moduleId=M02
      - moduleName="m02 borda"
      - contractRef=docs/architecture/contract/contract-v0.md
      - auditRef=docs/architecture/audit/audit-v0.md
      - interoperabilityRef=docs/architecture/interoperability/interoperability-v0.md
      - moduleDoc=development/v0.3/module-02-v0.3.md

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  appgear.io/module-id: M02
  appgear.io/module-name: "m02 borda"
