apiVersion: v1
kind: Service
metadata:
  name: appgear-m12-guardian-svc
  labels:
    appgear.io/module-id: M12
    appgear.io/module-name: "suite-guardian"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M12
    appgear.io/module-name: "suite-guardian"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
