apiVersion: v1
kind: Service
metadata:
  name: appgear-m03-observabilidade-svc
  labels:
    appgear.io/module-id: M03
    appgear.io/module-name: "observabilidade"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M03
    appgear.io/module-name: "observabilidade"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
