apiVersion: v1
kind: Service
metadata:
  name: appgear-m15-dr-backup-svc
  labels:
    appgear.io/module-id: M15
    appgear.io/module-name: "dr-backup"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M15
    appgear.io/module-name: "dr-backup"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
