apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appgear-security

resources:
  - namespace.yaml

configMapGenerator:
  - name: appgear-m05-metadata
    literals:
      - moduleId=M05
      - moduleName="m05 seguranca segredos"
      - contractRef=docs/architecture/contract/contract-v0.md
      - auditRef=docs/architecture/audit/audit-v0.md
      - interoperabilityRef=docs/architecture/interoperability/interoperability-v0.md
      - moduleDoc=development/v0.3/module-05-v0.3.md

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  appgear.io/module-id: M05
  appgear.io/module-name: "m05 seguranca segredos"
