apiVersion: v1
kind: Service
metadata:
  name: appgear-m05-seguranca-segredos-svc
  labels:
    appgear.io/module-id: M05
    appgear.io/module-name: "seguranca-segredos"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M05
    appgear.io/module-name: "seguranca-segredos"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
