apiVersion: v1
kind: Service
metadata:
  name: appgear-m04-bancos-core-svc
  labels:
    appgear.io/module-id: M04
    appgear.io/module-name: "bancos-core"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M04
    appgear.io/module-name: "bancos-core"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
