apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appgear-ops-policies

resources:
  - namespace.yaml

configMapGenerator:
  - name: appgear-m17-metadata
    literals:
      - moduleId=M17
      - moduleName="m17 politicas operacionais"
      - contractRef=docs/architecture/contract/contract-v0.md
      - auditRef=docs/architecture/audit/audit-v0.md
      - interoperabilityRef=docs/architecture/interoperability/interoperability-v0.md
      - moduleDoc=development/v0.3/module-17-v0.3.md

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  appgear.io/module-id: M17
  appgear.io/module-name: "m17 politicas operacionais"
