apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appgear-factory

resources:
  - namespace.yaml

configMapGenerator:
  - name: appgear-m09-metadata
    literals:
      - moduleId=M09
      - moduleName="m09 factory"
      - contractRef=docs/architecture/contract/contract-v0.md
      - auditRef=docs/architecture/audit/audit-v0.md
      - interoperabilityRef=docs/architecture/interoperability/interoperability-v0.md
      - moduleDoc=development/v0.3/module-09-v0.3.md

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  appgear.io/module-id: M09
  appgear.io/module-name: "m09 factory"
