apiVersion: v1
kind: Service
metadata:
  name: appgear-m09-factory-svc
  labels:
    appgear.io/module-id: M09
    appgear.io/module-name: "suite-factory"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M09
    appgear.io/module-name: "suite-factory"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
