apiVersion: v1
kind: Service
metadata:
  name: appgear-m11-operations-svc
  labels:
    appgear.io/module-id: M11
    appgear.io/module-name: "suite-operations"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M11
    appgear.io/module-name: "suite-operations"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
