apiVersion: apps/v1
kind: Deployment
metadata:
  name: appgear-m01-gitops-argo-controller
  labels:
    appgear.io/module-id: M01
    appgear.io/module-name: "gitops-argo"
spec:
  replicas: 1
  selector:
    matchLabels:
      appgear.io/module-id: M01
      appgear.io/module-name: "gitops-argo"
      appgear.io/role: controller
  template:
    metadata:
      labels:
        appgear.io/module-id: M01
        appgear.io/module-name: "gitops-argo"
        appgear.io/role: controller
    spec:
      containers:
        - name: controller
          image: quay.io/argoproj/argocd:latest
          ports:
            - containerPort: 80
          env:
            - name: MODULE_ID
              value: "M01"
            - name: MODULE_NAME
              value: "gitops-argo"
            - name: INTENDED_COMPONENTS
              value: "argocd,applicationsets,workflows,events"
