apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: appgear-identity

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: appgear-m06-metadata
    literals:
      - moduleId=M06
      - moduleName="identidade-sso"
      - contractRef=docs/architecture/contract/contract-v0.md
      - auditRef=docs/architecture/audit/audit-v0.md
      - interoperabilityRef=docs/architecture/interoperability/interoperability-v0.md
      - moduleDoc=development/v0.3/module-06-v0.3.md

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  appgear.io/module-id: M06
  appgear.io/module-name: "identidade-sso"
