apiVersion: apps/v1
kind: Deployment
metadata:
  name: appgear-m07-portal-backstage-controller
  labels:
    appgear.io/module-id: M07
    appgear.io/module-name: "portal-backstage"
spec:
  replicas: 1
  selector:
    matchLabels:
      appgear.io/module-id: M07
      appgear.io/module-name: "portal-backstage"
      appgear.io/role: controller
  template:
    metadata:
      labels:
        appgear.io/module-id: M07
        appgear.io/module-name: "portal-backstage"
        appgear.io/role: controller
    spec:
      containers:
        - name: controller
          image: ghcr.io/backstage/backstage:latest
          ports:
            - containerPort: 80
          env:
            - name: MODULE_ID
              value: "M07"
            - name: MODULE_NAME
              value: "portal-backstage"
            - name: INTENDED_COMPONENTS
              value: "backstage,catalog,plugins"
