apiVersion: v1
kind: Service
metadata:
  name: appgear-m07-portal-backstage-svc
  labels:
    appgear.io/module-id: M07
    appgear.io/module-name: "portal-backstage"
spec:
  type: ClusterIP
  selector:
    appgear.io/module-id: M07
    appgear.io/module-name: "portal-backstage"
    appgear.io/role: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
